/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as QpayRouteImport } from './routes/qpay.route'
import { Route as IndexRouteImport } from './routes/index.route'

// Create Virtual Routes

const WalletComponentImport = createFileRoute('/wallet')()
const SettingComponentImport = createFileRoute('/setting')()
const SendComponentImport = createFileRoute('/send')()
const ReceiveComponentImport = createFileRoute('/receive')()
const ImportWalletComponentImport = createFileRoute('/import-wallet')()
const BackupComponentImport = createFileRoute('/backup')()
const AboutComponentImport = createFileRoute('/about')()

// Create/Update Routes

const WalletComponentRoute = WalletComponentImport.update({
  path: '/wallet',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/wallet.component'),
    'component',
  ),
})

const SettingComponentRoute = SettingComponentImport.update({
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/setting.component'),
    'component',
  ),
})

const SendComponentRoute = SendComponentImport.update({
  path: '/send',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/send.component'),
    'component',
  ),
})

const ReceiveComponentRoute = ReceiveComponentImport.update({
  path: '/receive',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/receive.component'),
    'component',
  ),
})

const ImportWalletComponentRoute = ImportWalletComponentImport.update({
  path: '/import-wallet',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/import-wallet.component'),
    'component',
  ),
})

const BackupComponentRoute = BackupComponentImport.update({
  path: '/backup',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/backup.component'),
    'component',
  ),
})

const AboutComponentRoute = AboutComponentImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/about.component'),
    'component',
  ),
})

const QpayRouteRoute = QpayRouteImport.update({
  path: '/qpay',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/qpay': {
      preLoaderRoute: typeof QpayRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutComponentImport
      parentRoute: typeof rootRoute
    }
    '/backup': {
      preLoaderRoute: typeof BackupComponentImport
      parentRoute: typeof rootRoute
    }
    '/import-wallet': {
      preLoaderRoute: typeof ImportWalletComponentImport
      parentRoute: typeof rootRoute
    }
    '/receive': {
      preLoaderRoute: typeof ReceiveComponentImport
      parentRoute: typeof rootRoute
    }
    '/send': {
      preLoaderRoute: typeof SendComponentImport
      parentRoute: typeof rootRoute
    }
    '/setting': {
      preLoaderRoute: typeof SettingComponentImport
      parentRoute: typeof rootRoute
    }
    '/wallet': {
      preLoaderRoute: typeof WalletComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRouteRoute,
  QpayRouteRoute,
  AboutComponentRoute,
  BackupComponentRoute,
  ImportWalletComponentRoute,
  ReceiveComponentRoute,
  SendComponentRoute,
  SettingComponentRoute,
  WalletComponentRoute,
])

/* prettier-ignore-end */
