/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *
 */
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Providers } from '../lib/provider';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <AppRouterCacheProvider>
          <body>{children}</body>
        </AppRouterCacheProvider>
      </html>
    </Providers>
  );
}
